### ISSUE TITLE
How to parse datetime fields ?

### ISSUE THREAD

**Issue by piotrh** [mikeduglas/cJSON#1]
Hello !

In my JSON file I have a date + time field: 
{"dataWpisu": "2018-11-22 15:21:16", .........}

Is it possible to parse this whole field as a string ? Now it's being parsed as date and a part with time is lost.

**Comment by mikeduglas** [comment]
By default it parses as a string "2018-11-22 15:21:16" if you did not specify 'options' parameter for ToGroup or sibling method. Check the length of receiving field 'dataWpisu', it should be at least STRING(19).

**Comment by piotrh** [comment]
Thank you !
It was error in my code.
