### ISSUE TITLE
Parsing complex JSON

### ISSUE THREAD

**Issue by krosoftware** [mikeduglas/cJSON#3]
Hello Mike
I try to use your cJSON tool but can not even start :(

Here is JSON declaration and I'm not sure how to declare QUEUES to hold data.
Can you please give some help?

`
{
   "connections":[
      {
         "resourceName":"people/c6472698414630138457",
         "etag":"%Eg4BAgMFCQsQFS43PT4/QBoEAQIFByIMNXloQUF3UkwySHc9",
         "names":[
            {
               "metadata":{
                  "primary":true,
                  "source":{
                     "type":"CONTACT",
                     "id":"59d3a4ea0e437259"
                  }
               },
               "displayName":"john doe",
               "familyName":"doe",
               "givenName":"john",
               "displayNameLastFirst":"doe, john",
               "unstructuredName":"john doe"
            }
         ],
         "photos":[
            {
               "metadata":{
                  "primary":true,
                  "source":{
                     "type":"CONTACT",
                     "id":"59d3a4ea0e437259"
                  }
               },
               "url":"https://lh3.googleusercontent.com/cm/AATWAfsEQRQAv2jfjAksYtEgczIg5XI2BtlrYq0ieD-fixzLoGCnWOgH7S1LwRot2e40=s100",
               "default":true
            }
         ],
         "emailAddresses":[
            {
               "metadata":{
                  "primary":true,
                  "source":{
                     "type":"CONTACT",
                     "id":"59d3a4ea0e437259"
                  }
               },
               "value":"pero@pero.com"
            }
         ],
         "phoneNumbers":[
            {
               "metadata":{
                  "primary":true,
                  "source":{
                     "type":"CONTACT",
                     "id":"59d3a4ea0e437259"
                  }
               },
               "value":"656165"
            }
         ]
      },
      {
         "resourceName":"people/c0",
         "etag":"%Eg4BAgMFCQsQFS43PT4/QBoEAQIFByIMR1FZQll1c1k2K009",
         "names":[
            {
               "metadata":{
                  "primary":true,
                  "source":{
                     "type":"CONTACT",
                     "id":"0"
                  }
               },
               "displayName":"za mik",
               "familyName":"mik",
               "givenName":"za",
               "displayNameLastFirst":"mik, za",
               "unstructuredName":"za mik"
            }
         ],
         "photos":[
            {
               "metadata":{
                  "primary":true,
                  "source":{
                     "type":"CONTACT",
                     "id":"0"
                  }
               },
               "url":"https://lh3.googleusercontent.com/contacts/ABsqpluI96pFz8wCLE8UQB1WqI3poYeGTQR-aqLQy0NaildrGo4XHYiG=s100"
            },
            {
               "metadata":{
                  "source":{
                     "type":"PROFILE",
                     "id":"110257135952718338465"
                  }
               },
               "url":"https://lh3.googleusercontent.com/a-/AD5-WCkb2LmqzUTLUlhMQ1V9rxfSBdfmOHekz1kKMDSD=s100",
               "default":true
            }
         ],
         "emailAddresses":[
            {
               "metadata":{
                  "primary":true,
                  "source":{
                     "type":"CONTACT",
                     "id":"0"
                  },
                  "sourcePrimary":true
               },
               "value":"mas@gmail.com",
               "type":"other",
               "formattedType":"Other"
            },
            {
               "metadata":{
                  "source":{
                     "type":"CONTACT",
                     "id":"0"
                  }
               },
               "value":"za.mik@gmail.com",
               "type":"other",
               "formattedType":"Other"
            }
         ]
      }
   ],
   "totalPeople":2,
   "totalItems":2
}
`
Thanks in advance

**Comment by mikeduglas** [comment]
As I can see your json contains arrays inside arrays, this should be translated to Clarion as queues inside queues which is impossible. So you must decide which data you need to extract and define your Clarion structure(-s) accordingly.

**Comment by mikeduglas** [comment]
For example, look at examples\ParseJSON.clw.

**Comment by krosoftware** [comment]
Thank you but it works partially, it display only one record instead of two.
Here is code I used:

` 
 PROGRAM
  INCLUDE('cjson.inc')
  MAP
    ParseJSON()
  END

jsonStr                       STRING(256), AUTO

  CODE
  ParseJSON()

ParseJSON                     PROCEDURE()
jsonFactory                     cJSONFactory
jroot                           &cJSON
jNames                          &cJSON
names                           queue
displayName                       string(100)
                                .
L                               long
pJson                           cstring(4100000)
                                
  CODE
  
  pJson = clipboard()  ! here I pasted JSON value I previously posted (in my first post above)
  
  jRoot &= jsonFactory.Parse(pJson)
  jNames &= jRoot.FindObjectItem('names')
  IF NOT jNames &= NULL
    IF jNames.ToQueue(names)
      MESSAGE('names found: '& RECORDS(names))
      loop L = 1 to records(names)
      get(names, L)
        message(names.displayName)
      .
    ELSE
      MESSAGE('Error reading names')
    END
  ELSE
    MESSAGE('names not found')
  END
    
  !- cleanup
  jRoot.Delete()
`

Why it display only one record?

**Comment by mikeduglas** [comment]
Because FindObjectItem('names') finds first object with the name "names", which is an array of 1 element.

**Comment by krosoftware** [comment]
OK now I use FindArrayItem and it find only one "names" item, please check:
`
  PROGRAM
  INCLUDE('cjson.inc')
  MAP
    ParseJSON()
  END


  CODE
  ParseJSON()

ParseJSON            PROCEDURE()
jsonFactory                     cJSONFactory
root                            &cJSON
item                            &cJSON
p                               cstring(4100000)
  CODE

  p = clipboard()

  root &= jsonFactory.Parse(p)
  IF root &= NULL
    RETURN
  END

  item &= root.FindArrayItem('names', 1)
  IF NOT item &= NULL
    item &= item.GetObjectItem('displayName')
    IF NOT item &= NULL
      message(item.getStringValue())
    else
      message('no item')
    .  
  else
    message('nothing found')
  .  
  root.Delete()

`

If I put item &= root.FindArrayItem('names', 2), there is no value.
Thanks.

**Comment by mikeduglas** [comment]
Your json comtains 2 arrays with the name 'names', so this is the problem. FindArrayItem finds first one as well as FindObjectItem.
Below is the way using jsonpath:


```
  PROGRAM

  INCLUDE('cjson.inc'), ONCE
  INCLUDE('cjsonpath.inc'), ONCE

  MAP
    INCLUDE('printf.inc'), ONCE
  END

qNames                        QUEUE
metadata                        GROUP
primary                           BOOL
source                            GROUP
typ                                 STRING(20), NAME('type')  !- "type" field label is not allowed
id                                  STRING(20)
                                  END
                                END
familyName                      STRING(20)
givenName                       STRING(20)
                              END

jParser                       cJSONFactory
jRoot                         &cJSON
jName                         &cJSON
output                        TCJsonPathResultAccumulator
resCount                      LONG, AUTO
i                             LONG, AUTO

  CODE
  !- parse json file
  jRoot &= jParser.ParseFile('test.json')
  IF NOT jRoot &= NULL
    FREE(qNames)
    
    !- find all 'names' objects
    resCount = jRoot.FindPathContext('$[connections][..][names]', output)
    LOOP i=1 TO resCount
      !- add each name to the queue
      jName &= output.GetObject(i)
      printd('name: %s', jName.ToString())  !- log name object
      jName.ToQueue(qNames,, '[{{"name":"primmary", "isbool":true}]')
    END
    printd('%|')
    
    !- check names queue
    LOOP i=1 TO RECORDS(qNames)
      GET(qNames, i)
      printd('name[%i]: %s %s', i, qNames.familyName, qNames.givenName)
      printd('  primary: %b, type "%s", id "%s"', | 
        qNames.metadata.primary, qNames.metadata.source.typ, qNames.metadata.source.id)
    END
      
    
    jRoot.Delete()
  END
 
```

**Comment by krosoftware** [comment]
Awesome, thank you so much. It works perfect.
