### ISSUE TITLE
How to force get number value as STRING?

### ISSUE THREAD

**Issue by FlavioSuarez** [mikeduglas/cJSON#4]
Hi!

I parse some JSON files from several sources and not have control about its content...
Some JSON files have an item
  "serialNumber": "56236298113681991290374258307",
which is parsed OK using GetValue().

But other JSON files have an item
  "serialNumber": 417610737815768073,
(as number) wich is not parsed OK using GetValue() neither using GetStringValue().

Example file:
{ "serialNumber": 417610737815768073,
  "serialNumber2": "56236298113681991290374258307",
  "author":{
    "first_name": "Ms R",
    "last_name":"Reddy"
  }
}

jItem &= jRoot.FindObjectItem( 'serialNumber')
strValue = jItem.GetValue()     ! strValue is wrong
    
jItem &= jRoot.FindObjectItem( 'serialNumber2')
strValue = jItem.GetValue()     ! strValue is OK

How to force get the SerialNumber value as STRING?

TIA!
Best regards

**Comment by mikeduglas** [comment]
Hi Flavio,

New release (v1.41) extends GetStringValue for numeric values:
```
jItem &= jRoot.FindObjectItem( 'serialNumber')
strValue = jItem.GetStringValue()  !- string value '417610737815768073'
```
Please check and let me know if it does work.
Thanks for the feedback.

**Comment by FlavioSuarez** [comment]
Wow! This was really fast!
Works like a charm!
Thank you so much!!
